bin/main_LQS.exe:src/list-copy.cpp src/main_LQS.cpp src/file.hpp src/pile.hpp
	@echo Compilation en cours...
	@g++ -W -Wall -lm src/list-copy.cpp src/main_LQS.cpp -o bin/main_LQS.exe

run: bin/main_LQS.exe
	@bin/main_LQS.exe
.PHONY:
	run