
* Exercice1

La taille de la deuxieme image sera 4 fois plus grande que la première.

* Exercice2

Une image de résolution 640*480 a 307200 points. Lorsque l'image est enregistrée en
niveau de gris chaque point est stocké dans un octets. La taille de l'image sera
donc de 307200 octets, ie 300 kio.

Lorsque l'image est stockée en vraies couleurs chaque point est stocké dans 3
ocets(RVB). La taille de l'image sera donc de 307200 * 3 ocets = 900 kio.

Dans une image de 1920*1080 il y a 2073600 points.
Chaque point est stocké dans 4 octets donc la taille de l'image est 
de 2073600 * 3 octets = 6075 kio

Dans une image de 3840*2160 il y a 8294400 points.
L'image sera donc de 8294400*3 octets = 24300 kio

* Exercice3

R=149(%58)
V=175(69%)
B=29(11%)

Teinte=71°
Sat=83%
Valeur=69%

Cyan=15%
Magenta=0%
Jaune=83%
Noir=31%

Hexa=95af1d

* Exercice4

Quand on zoom le point prend de plus en plus de pixels.

* Exercice5

On prend affiche la valeur RVG de la couleur indéxée du pixel 320/314

* Exercice6

Il s'agit de l'image de droite car on peut distinguer les pixels.
Cela est du au fait qu'elle ne peut pas représenter suffisemment de couleurs
différentes pour afficher convenablement le dégradé de blanc de la fleur.

* Exercice7

Lorsqu'il y a des courbres la compression détériore grandement 
la qualité de l'image.

Les dégradés deviennent de plus en plus uniformes lorsqu'on réduit la 
qualités.

On remarque aussi qu'il y a des taches à côtés des lettres du texte
lorsqu'on réduit la qualité.

* Exercice8
En traçant la courbe d'évolution de la taille des fichiers en fonction 
de la qualité définite on remarque que l'on a le meilleur raport qualité/taille
à 75.

* Exercice9
On ne peut observer qu'un seul canal car l'image est en format gif, ce qui
fait que chaque pixel est codé avec une palette de couleur prè-construite et
non avec un codage RGB.

* Exercice10
Il y en a 255.

* Exercice11

Les lumières proches du rouge sont absorbées par l'eau de mer, ce qui fait
qu'à basse-profondeur on aura une aténuation des rouges sur les photos.

* Exercice12

Il manque du rouge.

* Exercice13

L'image devient noire.
Une matrice de convolution est une matrice carré de dimension impaire qui modifie 
la valueur de chaque pixel.On crée une matrice de meme dimentsion que celle de convolution
avec le pixel que l'on veut modifier. On multiplie ensuite les coefficents des deux matrices
entre eux. La valeur du nouveau pixel sera égale à la somme des coefficents de la matrice obtenue.


Ici vu que notre matrice de covolution est nulle la valeur finale du pixel sera nécessairement
0, ce qui fait que tous les pixels de l'image seront noirs.

* Exercice14

  C'est psychédélique.
