.PHONY:
	run
bin/main_Date.exe: src/Date.cpp src/main_Date.cpp
	@echo "Compilation en cours ..."
	@g++ -Wall -W src/Date.cpp src/main_Date.cpp -o bin/main_Date.exe
run: bin/main_Date.exe
	@./bin/main_date.exe