.PHONY:
	run
bin/main-list-copy: src/list-copie.cpp src/main-list-copy.cpp
	@echo Compilation en cours...
	@g++ -W -Wall -lm src/list-copie.cpp src/main-list-copy.cpp -o bin/main-list-copy

run: bin/main-list-copy
	@./bin/main-list-copy